### ISSUE TITLE
An additional package and a few other steps required to build in Ubuntu

### ISSUE THREAD

**Issue by Paulls20** [nedrysoft/pingnoo#10]
Compilation error without installing qttools5-dev.

qttools5-dev package contains `QtUiPlugin/QDesignerCustomWidgetInterface` which is required to build Ribbon.
`sudo apt-get install qttools5-dev`

Also in Ubuntu 20.04 setcap is located in `/sbin/setcap`

**Comment by fizzyade** [comment]
> Compilation error without installing qttools5-dev.
> 
> qttools5-dev package contains `QtUiPlugin/QDesignerCustomWidgetInterface` which is required to build Ribbon.
> `sudo apt-get install qttools5-dev`
> 

Thanks, fixed in https://github.com/nedrysoft/pingnoo/tree/7b897d76d4ee99316c43c9e322b283b4b8a29407

> Also in Ubuntu 20.04 setcap is located in `/sbin/setcap`

I can't find a reference to this, the postinst script doesn't use the full path, just the binary name, I've done a search through the project and can't find it anywhere, can you tell me where it is please?

Thanks for taking the time to provide these details, much appreciated!

**Comment by Paulls20** [comment]
Fixed in https://github.com/nedrysoft/pingnoo/pull/11
