### ISSUE TITLE
ucrtbased.dll missing on Windows 10

### ISSUE THREAD

**Issue by cknoerle** [nedrysoft/pingnoo#4]
I just installed Pingnoo.2021.01.10-develop.x86_64.exe on Windows 10 Enterprise 20H2.
When I start pingnoo from the startmenu an error is shown (translated from German):

Code execution cannot continue, because ucrtbased.dll was not found. Reinstalling the program potentially fixes the problem.

**Comment by fizzyade** [comment]
> I just installed Pingnoo.2021.01.10-develop.x86_64.exe on Windows 10 Enterprise 20H2.
> When I start pingnoo from the startmenu an error is shown (translated from German):
> 
> Code execution cannot continue, because ucrtbased.dll was not found. Reinstalling the program potentially fixes the problem.

I will take a look, in the meantime can you try installing the VS2019 redist (link below is from Microsoft) to see if it fixes the issue, the installer itself should install this.  The "d" on the end of the file implies it's a debug build, so maybe I messed something up slightly.

https://aka.ms/vs/16/release/vc_redist.x64.exe

Edit:

I will need to try this in a clean virtual machine, I don't get the problem on my development machine even when clearing the PATH environment variable and launching from a terminal.

**Comment by fizzyade** [comment]
@cknoerle Thanks for your report on this, for some reason when it built it build against debug libraries and that is the cause of the issue.

I have rebuilt the installer against that version and it correctly built and packaged the release version, I've checked it in a clean Windows 10 VM and it works correctly now.

There is an outstanding issue on the Windows version, I need to bundle the OpenSSL libraries as well, currently, they're not included and on windows that prevent the geo-ip lookup from working, you can see in the Components dialog that the geo-IP components failed to load because of this.  It's not a major issue, but I'm working towards another release soon which includes a working settings dialog.

Let me know if the installer now works for you, it should do!

**Comment by cknoerle** [comment]
Is there a new build/release with this fix? GH release page still only shows the release I had tried before.

**Comment by fizzyade** [comment]
> Is there a new build/release with this fix? GH release page still only shows the release I had tried before.

Yes. I rebuilt the windows binary from that revision.  The file has been replaced, just download it again.

**Comment by cknoerle** [comment]
Works now, thank you!
