### ISSUE TITLE
Slight bug with Host # 10 while scanning yandex.ru

### ISSUE THREAD

**Issue by sxiii** [nedrysoft/pingnoo#92]
Attaching screenshot. Something wrong with node # 10 in here:
![Screenshot_2021-10-24_02-23-04](https://user-images.githubusercontent.com/575925/138575239-45981cd3-d767-4103-a8b5-90614829ec5f.png)

**Comment by fizzyade** [comment]
That looks like normal behaviour, what is the problem?

That trace shows only that hop 10 did not respond with a TTL exceeded message, I can't tell whether that is right or wrong from the screenshot.

What does trace route from a terminal return to the same host?

Also which version are you running, is it a native distribution package or the AppImage?

Also the ping engine you are using (ping executable) is provided as a workaround for raw packets which cannot be created without root privileges.  

The native packaged versions use setcap on installation which allows them to be run by a non superuser.

The ping executable ping engine is not as accurate with timing due to it spawning tasks.

Thanks

**Comment by sxiii** [comment]
Seems like you're right. I've tried RPM package on Fedora and got similar result: 
![image](https://user-images.githubusercontent.com/575925/139257826-35033927-7e15-42c1-98b5-853be6509b61.png)

This is from Fedora (the first screenshot in the issue was from Arch) and this also has this stripes. Here is traceroute to the same host from the same provider:
```
(base) [sm@fedora-mbp ~]$ traceroute yandex.ru
traceroute to yandex.ru (5.255.255.88), 30 hops max, 60 byte packets
 1  * * *
 2  185.78.231.1 (185.78.231.1)  9.651 ms  10.276 ms  12.337 ms
 3  193.58.241.208 (193.58.241.208)  10.713 ms  12.911 ms  12.451 ms
 4  31.169.48.98 (31.169.48.98)  14.234 ms  15.271 ms  13.524 ms
 5  te-0-0-0-19.ncs-am5-ams.blix.com (31.169.49.34)  27.323 ms  27.611 ms  28.050 ms
 6  ams-ix-am1.yandex.net (80.249.211.200)  29.274 ms  30.019 ms  30.014 ms
 7  10.2.5.1 (10.2.5.1)  60.961 ms 10.4.5.1 (10.4.5.1)  58.123 ms  57.075 ms
 8  yandex.ru (5.255.255.88)  53.561 ms  52.375 ms  52.520 ms
```
Both was "native" versions (kinda). Also, tried running as root on Fedora and using both "ping" and "ICMP Socket". Both results got these red stripes at some points.

Thanks for your help and answers as usual!
